- hosts: localhost
  sudo: yes
  remote_user: vagrant
  tasks:
  - name: apt-get update
    command: sudo apt-get update
  - name: Instalar todos los paquetes necesarios para la aplicacion
    apt: name=python-setuptools state=present
    apt: name=build-essential state=present
    apt: name=python-dev state=present
    apt: name=git state=present
  - name: Clonar repositorio gestionPedidos de git
    git: repo=https://github.com/ignaciorecuerda/gestionpedidos_django.git  dest=gestionPedidos version=HEAD force=yes
  - name: Damos permisos de ejecucion a la carpeta gestionPedidos
    command: chmod -R +x gestionPedidos
  - name: Instala python-dev
    command: sudo apt-get install python-dev -y
  - name: Instala dependencias pillow
    command: sudo apt-get install libtiff5-dev libjpeg8-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python-tk -y
  - name: instalo pip
    apt: name=python-pip state=present
  - name: instala pillow
    command: sudo pip install pillow 
  - name: Instalar todos los requeriments 
    command: sudo pip install -r gestionPedidos/requirements.txt
  - name: lanzamos aplicacion
    command: nohup sudo python gestionPedidos/manage.py runserver 0.0.0.0:80
    register: lanzaAplicacion
  - debug: msg="{{ lanzaAplicacion.stdout }}"
  - debug: msg="{{ lanzaAplicacion.stderr }}"