- hosts: ubuntu14
  sudo: yes
  remote_user: nacho2
  tasks:
  - name: Instalar todos los paquetes necesarios para la aplicacion
    apt: name=python-setuptools state=present
    apt: name=build-essential state=present
    apt: name=python-dev state=present
    apt: name=git state=present
  - name: Clonar repositorio gestionPedidos de git
    git: repo=https://github.com/ignaciorecuerda/gestionpedidos_django.git  dest=~/gestionPedidos version=HEAD
  - name: Damos permisos de ejecucion a la carpeta gestionPedidos
    command: chmod -R +x ~/gestionPedidos
  - name: Instalar todos los requeriments 
    command: sudo pip install -r ~/gestionPedidos/dfgsdfgsdfg
  - name: lanzamos aplicacion
    command: sudo python gestionPedidos/tango_with_django_project/manage.py runserver 0.0.0.0:80
